app/models/product.py
from app.models.base import Base
from sqlalchemy import Integer, String, DateTime
from sqlalchemy.orm import mapped_column, relationship
from sqlalchemy import func
from app.models.review import Review

class Product(Base):
    __tablename__ = "product"

    id = mapped_column(Integer, primary_key=True, autoincrement=True)
    name = mapped_column(String(200), nullable=False)
    price = mapped_column(Integer)
    description = mapped_column(String(300), nullable=False)
    created_at = mapped_column(DateTime(timezone=True), server_default=func.now())
    
    # Relationship list
    reviews = relationship("Review", cascade="all,delete-orphan")

    def __repr__(self):
        return f'<Product {self.name}>'

app/controllers/product.py
from flask import Blueprint, render_template, request, jsonify
from app.connectors.mysql_connector import engine

from app.models.product import Product
from sqlalchemy import select
from flask_login import current_user, login_required

from sqlalchemy.orm import sessionmaker
from app.utils.api_response import api_response

from app.decorators.role_checker import role_required

from cerberus import Validator
from app.validations.product_schema import product_schema

from flask_jwt_extended import jwt_required, get_jwt

# Definisikan Blueprint untuk rute-rute terkait produk
product_routes = Blueprint('product_routes', __name__)

# Tentukan rute untuk URL '/product' 
# diprotect menggunakan @login_required

@product_routes.route("/product", methods=['GET'])
@login_required
def product_home():
    response_data = dict()
    connection = engine.connect()
    Session = sessionmaker(connection)
    session = Session()
    try:
        product_query = select(Product)

        # Penambahan filter apabila menggunakan search_query
        if request.args.get('query') != None:
            search_query = request.args.get('query')
            product_query = product_query.where(Product.name.like(f'%{search_query}%'))

        products = session.execute(product_query)
        products = products.scalars()
        response_data['products'] = products
 
        response_data['name'] = current_user.name

        # Render template HTML 'product_home.html' dari direktori 'templates/products/'
        return render_template("products/product_home.html", response_data = response_data)

    except Exception as e:
        return api_response(
            status_code=500,
            message=str(e),
            data={}
        )
    
@product_routes.route("/product", methods=['POST'])
@role_required('Admin')
def product_insert():

    v = Validator(product_schema)
    json_data = request.get_json()
    if not v.validate(json_data):
        # Validate Gagal
        return jsonify({"error": v.errors}), 400
    
    # new_product = Product(
    #         name=request.form['name'], 
    #         price=request.form['price'], 
    #         description=request.form['description']
    #     )
    
    new_product = Product(
            name=json_data['name'], 
            price=json_data['price'], 
            description=json_data['description']
        )
    
    connection = engine.connect()
    Session = sessionmaker(connection)
    session = Session()
    session.begin()
    try:
        session.add(new_product)
        session.commit()

    except Exception as e:
        # Operation jika gagal
        session.rollback()
        return api_response(
            status_code=500,
            message=str(e),
            data={}
        )
    
    # Operation sukses
    return { "message": "Input data berhasil"}

@product_routes.route("/product/<id>", methods=['DELETE'])
@role_required('Admin')
def product_delete(id):
    connection = engine.connect()
    Session = sessionmaker(connection)
    session = Session()
    session.begin()
    try:
        product_to_delete = session.query(Product).filter(Product.id==id).first()
        session.delete(product_to_delete)
        session.commit()
        # Operation sukses
        return {"message":"Data detail pembelian berhasil dihapus"}
    
    except Exception as e:
        session.rollback()
        return api_response(
            status_code=500,
            message=str(e),
            data={}
        ) 
    
@product_routes.route("/product/<id>", methods=['PUT'])
@jwt_required()
def product_update(id):
    connection = engine.connect()
    Session = sessionmaker(connection)
    session = Session()
    session.begin()
    try:
        product_to_update= session.query(Product).filter(Product.id==id).first()
        
        product_to_update.name = request.form['name']
        product_to_update.price = request.form['price']
        product_to_update.description = request.form['description']
        
        session.commit()
        # Operation sukses
        return {"message":"Data detail pembelian berhasil diedit"}
    
    except Exception as e:
        session.rollback()
        return api_response(
            status_code=500,
            message=str(e),
            data={}
        ) 
    

app/templates/products/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product List</title>
    <style>

        body {
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background-color: #f0f0f0;
        }

        .container {
            max-width: 600px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        
        header{
            display: flex;
            justify-content: center;
            text-align: center;
        }

        .user-access {
            margin-top: 50px;
            display: flex;
            justify-content: center;
            align-items: center;
            gap: 12px;
        }
        
        footer {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;


        }

        footer, h4{
            margin-top: 50px;
            margin-bottom: 30px;
        }
        
        .search-button {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }

        .product-list {
            list-style-type: none;
            padding: 0px 50px 0px 50px;
            text-align:justify;
        }

        .product-list li {
            margin-bottom: 10px;
        }

        /* Responsiveness for Mobile Devices */
        @media only screen and (max-width: 600px) {
            header {
                font-size: 20px; 
            }
            .search-button {
                padding: 8px 16px; 
                font-size: 14px; 
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Hello, my Module-7 Assignment here</h1>
        </header>
    
        <main>
            <section class="product-list">
                <p>Tugas ini mengimplementasikan operasi dasar CRUD (Create(POST), 
                    Read(GET), Update(PUT), Delete(DELETE)). 
                    Selain itu, dalam proyek ini akan mengeksplorasi 
                    metode otentikasi berbasis sesi Atau 
                    berbasis token menggunakan Flask-login 
                    dan Flask-JWT-Extended.
                </p>
            </section>
        
            <section class="user-access">
                <!-- Menggunakan JavaScript untuk mengarahkan ke halaman register saat tombol diklik -->
                <button class="search-button" onclick="window.location.href='/register'">Register Here</button>
                <!-- Menggunakan JavaScript untuk mengarahkan ke halaman login saat tombol diklik -->
                <button class="search-button" onclick="window.location.href='/login'">Login Here</button>
            </section>
        </main>
    
        <footer>
            <h4 id="current-time"></h4>
            <p ><i>copyright &copy; 2023-2024 by imanmaris</i></p>
        </footer>
    </div>


    <script>
        // Fungsi untuk memperbarui waktu saat ini setiap detik
        function updateCurrentTime() {
            var currentTime = new Date();
            var options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
            var dateTimeString = currentTime.toLocaleDateString('en-US', options);
            var hours = currentTime.getHours();
            var minutes = currentTime.getMinutes();
            var seconds = currentTime.getSeconds();
            // Format waktu dengan menambahkan nol jika kurang dari 10
            hours = (hours < 10 ? "0" : "") + hours;
            minutes = (minutes < 10 ? "0" : "") + minutes;
            seconds = (seconds < 10 ? "0" : "") + seconds;
            var timeString = hours + ":" + minutes + ":" + seconds;
            // Perbarui elemen HTML dengan tanggal dan waktu saat ini
            document.getElementById("current-time").innerHTML = dateTimeString + " " + timeString;
        }

        // Panggil fungsi updateCurrentTime setiap detik
        setInterval(updateCurrentTime, 1000);
    </script>
</body>
</html>

app/templates/products/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Reviews</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h2>Product Details</h2>
    <button>Back</button>

    <div>
        <h3>Product Name: Product A</h3>
        <p>Price: $10.00</p>
        <p>Rating: 4.5</p>
    </div>

    <h2>Product Reviews</h2>
    <table>
        <thead>
            <tr>
                <th>Email</th>
                <th>Rating</th>
                <th>Review Content</th>
                <th>Created Datetime</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>example1@example.com</td>
                <td>4</td>
                <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</td>
                <td>2024-02-09 08:30:45</td>
            </tr>
            <tr>
                <td>example2@example.com</td>
                <td>5</td>
                <td>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</td>
                <td>2024-02-08 12:15:30</td>
            </tr>
            <!-- Add more <tr> elements for additional reviews -->
        </tbody>
    </table>
</body>
</html>

app/templates/products/product_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product List</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        button {
            padding: 5px 10px;
            cursor: pointer;
        }

        .search-container {
            margin-top: 20px;
        }
        
        .search-input {
            padding: 10px;
            width: 300px;
            border-radius: 5px;
            border: 1px solid #ccc;
            font-size: 16px;
        }
        
        .search-button {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <div>
        Hello, {{response_data['name']}}
        <a href="/logout">Logout</a>
    </div>
    <h2>Product List</h2>
    <button onclick="openNewProductForm()">Add New Product</button>
    <div class="search-container">
        <input type="text" class="search-input" id="searchInput" placeholder="Search...">
        <button class="search-button" onclick="search()">Search</button>
    </div>
    <hr style="border:none;"/>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Price</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for product in response_data['products'] %}
            <tr>
                <td>{{product.id}}</td>
                <td>{{product.name}}</td>
                <td>{{product.price}}</td>
                <td>{{product.description}}</td>
                <td>
                    <button>Review</button>
                    <button id="edit_{{product.id}}" onclick="openEditProductForm(this)">Edit</button>
                    <button id="delete_{{product.id}}" onclick="deleteProduct(this)">Delete</button>
                </td>
            </tr>
            {% endfor %}
            <!-- Add more <tr> elements for additional products -->
        </tbody>
    </table>

    <div id="newProductForm" style="display: none;">
        <h3 id="formSection">Add New Product</h3>
        <form id="productForm">
            <label for="productName">Product Name:</label>
            <input type="text" id="productName" name="productName"><br><br>
            <label for="productPrice">Price:</label>
            <input type="number" id="productPrice" name="productPrice"><br><br>
            <label for="productDescription">Description:</label><br>
            <textarea id="productDescription" name="productDescription" rows="4" cols="50"></textarea><br><br>
            <button type="button" onclick="submitForm()">Submit</button>
            <button type="button" onclick="closeNewProductForm()">Cancel</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

    <script>
        var form_url = "";
        var form_method = "";
        var base_url = "{{ url_for('product_routes.product_home') }}";
        
        function openNewProductForm() {
            form_method = 'POST';
            form_url = base_url;
            document.getElementById("newProductForm").style.display = "block";
            document.getElementById("formSection").innerHTML = "Add New Product";
            document.getElementById("productForm").reset();
        }

        // function openEditProductForm(button) {
        //     var selected_product_id = button.id.split("_")[1];
        //     form_method = 'PUT';
        //     form_url = base_url + "/" + selected_product_id;

        //     var name = $('#name_'+selected_product_id).html();
        //     var price = $('#price_'+selected_product_id).html();
        //     var desc = $('#desc_'+selected_product_id).html();

        //     $('#productName').val(name);
        //     $('#productPrice').val(price);
        //     $('#productDescription').val(desc);

        //     document.getElementById("newProductForm").style.display = "block";
        //     document.getElementById("formSection").innerHTML = "Edit Product";
        // }

        function openEditProductForm(button) {
            var selected_product_id = button.id.split("_")[1];
            var edit_url = base_url + "/" + selected_product_id

            var requestData = {
                name: $('#productName').val(),
                price: $('#productPrice').val(),
                description: $('#productDescription').val()
            };

            $.ajax({
                url: edit_url,
                type: 'PUT',
                contentType: 'application/json',
                data: JSON.stringify(requestData),
                success: function(response) {
                    alert(response.message); // Tampilkan pesan respons dari backend
                    location.reload(); // Muat ulang halaman setelah berhasil diperbarui
                },
                error: function(xhr, status, error) {
                    alert("Terjadi kesalahan: " + error); // Tampilkan pesan kesalahan jika permintaan gagal
                }
            });
        }

        function closeNewProductForm() {
            document.getElementById("newProductForm").style.display = "none";
        }

        function submitForm(){
            var request_data = {
                name: $('#productName').val(),
                price: parseInt($('#productPrice').val()),
                description: $('#productDescription'). val()
            }

            $.ajax({
                url: form_url,
                data: JSON.stringify (request_data),
                method: form_method,
                headers: {
                    "Content-type" : "application/json"
                }
            }).done(function(response){
                alert(response.message);
                location.reload();
            })
        }

        function deleteProduct(button){
            var selected_product_id = button.id.split("_")[1];
            var delete_url = base_url + "/" + selected_product_id

             // Mencetak nilai selected_product_id dan delete_url ke konsol
            console.log("ID produk yang akan dihapus:", selected_product_id);
            console.log("URL yang akan digunakan untuk menghapus produk:", delete_url);

            $.ajax({
                url: delete_url,
                method: "DELETE"
            }).done(function(response){
                alert(response.message);
                location.reload();
            })
        }

        function search(){
            window.location = base_url + "?query=" + $('#searchInput').val();
        }
    </script>
</body>
</html>